import { sidebar } from "vuepress-theme-hope";

export const enSidebar = sidebar({
  "/docs/": [
    {
      text: "Getting Started",
      icon: "rocket",
      link: 'introduction',
      collapsible: false,
      children: [
        'installation',
        'structure',
        'configuration',
        'deployment',
        'cloud',
      ],
    },
    {
      text: "Architecture",
      icon: "sitemap",
      collapsible: true,
      prefix: "architecture/",
      link: 'architecture/',
      children: [
        'adapters',
        'context',
        'kernel',
        'container',
        'providers',
      ],
    },
    {
      text: "Essentials",
      icon: "star",
      collapsible: true,
      prefix: "essentials/",
      link: 'essentials/',
      children: [
        'validation',
        'error',
        'logging',
      ],
    },
    {
      text: "HTTP",
      icon: "server",
      collapsible: true,
      prefix: "http/",
      link: 'http/',
      children: [
        'lifecycle',
        'routing',
        'request',
        'response',
        'controller',
        'middleware',
        'urls',
        'cookies',
        'session',
      ],
    },
    {
      text: "Digging Deeper",
      icon: "book-open-reader",
      collapsible: true,
      prefix: "deeper/",
      link: 'deeper/',
      children: [
        'events',
        'console',
        'i18n',
        'storage',
        'http-client',
      ],
    },
    {
      text: "Database",
      icon: "database",
      collapsible: true,
      prefix: "database/",
      link: 'database/',
      children: [
        'nosql',
        'sql',
        'schemas',
        'seeding',
      ],
    },
    {
      text: "Security",
      icon: "shield",
      collapsible: true,
      prefix: "security/",
      link: 'security/',
      children: [
        'authentication',
        'authorization',
        'encryption-hashing',
        'cors',
        'csrf',
        'rate-limiting',
      ],
    },
    {
      text: "Cloud",
      icon: "cloud",
      collapsible: true,
      prefix: "cloud/",
      link: 'cloud/',
      children: [
        'adapters',
      ],
    },
    {
      text: "Testing",
      icon: "circle-check",
      collapsible: true,
      prefix: "testing/",
      link: 'testing/',
      children: [
        'libraries',
        'http',
        'console',
        'mocking',
        'database',
      ],
    },
  ],
});
