<template><div><p>Logging is effortless and extensible in Stone.js.</p>
<p>At its core, Stone.js provides a built-in logging utility through a console-based singleton logger. This default logger is designed for simplicity — it's available globally, context-aware, and ready to use without configuration.</p>
<p>But that's just the beginning.</p>
<p>The logger system in Stone.js is fully integrated into the Continuum Architecture, meaning it works seamlessly across all dimensions: setup, initialization, and integration. You can access it from lifecycle hooks, middleware, event handlers, services and so on. The default implementation is perfect for development and prototyping — but when you need more power, you can replace it entirely with your own logger (like <a href="https://getpino.io/#/" target="_blank" rel="noopener noreferrer">pino</a> or <a href="https://github.com/winstonjs/winston" target="_blank" rel="noopener noreferrer">winston</a>).</p>
<p>Stone.js treats logging like any other part of your internal context: injectable, configurable, and replaceable.</p>
<p>Logging is not just for debugging — it's a first-class citizen in the Stone.js ecosystem. Whether you're building a CLI tool, a backend microservice, or a frontend app, the logger is always there, fluent with your context.</p>
<h2 id="using-logger" tabindex="-1"><a class="header-anchor" href="#using-logger"><span>Using Logger</span></a></h2>
<h3 id="access-the-logger" tabindex="-1"><a class="header-anchor" href="#access-the-logger"><span>Access the Logger</span></a></h3>
<p>Stone.js gives you multiple ways to access the logger, depending on the context you're in. The default logger is available as a singleton, but it’s also automatically injected into the system's internal context during setup — so no need for global imports, you can just inject it where you need it.</p>
<h4 id="global-singleton-anywhere" tabindex="-1"><a class="header-anchor" href="#global-singleton-anywhere"><span>Global Singleton (Anywhere)</span></a></h4>
<p>The simplest way to log from anywhere in your code is by using the singleton instance:</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> Logger <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@stone-js/core'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">export</span> <span class="token keyword">const</span> <span class="token function-variable function">myEventHandler</span> <span class="token operator">=</span> <span class="token punctuation">(</span>event<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">  Logger<span class="token punctuation">.</span><span class="token function">info</span><span class="token punctuation">(</span><span class="token string">'Received event!'</span><span class="token punctuation">,</span> event<span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Use this approach when you're not inside an injected context like a function-based service, middleware, or lifecycle hook.
But avoid it in constructors if you can inject <code v-pre>logger</code> properly.</p>
<h4 id="contextual-injection-preferred" tabindex="-1"><a class="header-anchor" href="#contextual-injection-preferred"><span>Contextual Injection (Preferred)</span></a></h4>
<p>In most cases, you should inject the logger into your modules. This is the preferred way to access the logger, as it keeps your code clean and testable.</p>
<Tabs id="43" :data='[{"id":"Class-based"},{"id":"Factory-based"}]' :active="0" tab-id="class-factory-function">
<template #title0="{ value, isActive }">Class-based</template>
<template #title1="{ value, isActive }">Factory-based</template>
<template #tab0="{ value, isActive }">
<h5 id="class-based" tabindex="-1"><a class="header-anchor" href="#class-based"><span>Class-based</span></a></h5>
<p>For class-based modules, like services or event handlers, the logger is injected into the constructor:</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> Service<span class="token punctuation">,</span> ILogger <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@stone-js/core'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token decorator"><span class="token at operator">@</span><span class="token function">Service</span></span><span class="token punctuation">(</span><span class="token punctuation">{</span> alias<span class="token operator">:</span> <span class="token string">'MyService'</span> <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">MyService</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token keyword">private</span> <span class="token keyword">readonly</span> logger<span class="token operator">:</span> ILogger<span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">constructor</span><span class="token punctuation">(</span><span class="token punctuation">{</span> logger <span class="token punctuation">}</span><span class="token operator">:</span> <span class="token punctuation">{</span> logger<span class="token operator">:</span> ILogger <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">this</span><span class="token punctuation">.</span>logger <span class="token operator">=</span> logger<span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">doSomething</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">this</span><span class="token punctuation">.</span>logger<span class="token punctuation">.</span><span class="token function">info</span><span class="token punctuation">(</span><span class="token string">'Service method executed'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>Tip</strong>: Avoid accessing the global <code v-pre>Logger</code> singleton in constructors — always prefer injection. This keeps your code clean, testable, and aligned with the Continuum.</p>
</template>
<template #tab1="{ value, isActive }">
<h5 id="factory-based" tabindex="-1"><a class="header-anchor" href="#factory-based"><span>Factory-based</span></a></h5>
<p>For factory-based modules, like a middleware, the logger can be accessed through the <code v-pre>context</code> parameter:</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">export</span> <span class="token keyword">const</span> <span class="token function-variable function">MyBlueprintMiddleware</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">{</span> logger <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token keyword">return</span> <span class="token punctuation">(</span>context<span class="token punctuation">,</span> next<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">    logger<span class="token punctuation">.</span><span class="token function">info</span><span class="token punctuation">(</span><span class="token string">'Blueprint middleware triggered'</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">return</span> <span class="token function">next</span><span class="token punctuation">(</span>context<span class="token punctuation">)</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
</Tabs>
<h3 id="logger-api" tabindex="-1"><a class="header-anchor" href="#logger-api"><span>Logger API</span></a></h3>
<p>The logger in Stone.js follows a minimal and strict contract, defined by the <code v-pre>ILogger</code> interface. Whether you're using the built-in logger or your own, the same interface applies.</p>
<p>The default implementation is <code v-pre>ConsoleLogger</code>, which internally uses the native <code v-pre>console</code> methods and respects your blueprint configuration.</p>
<h4 id="ilogger-interface" tabindex="-1"><a class="header-anchor" href="#ilogger-interface"><span>ILogger Interface</span></a></h4>
<p>The interface defines the following methods:</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">export</span> <span class="token keyword">interface</span> <span class="token class-name">ILogger</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token function">info</span><span class="token punctuation">(</span>message<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> <span class="token operator">...</span>optionalParams<span class="token operator">:</span> <span class="token builtin">unknown</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span></span>
<span class="line">  <span class="token function">debug</span><span class="token punctuation">(</span>message<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> <span class="token operator">...</span>optionalParams<span class="token operator">:</span> <span class="token builtin">unknown</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span></span>
<span class="line">  <span class="token function">warn</span><span class="token punctuation">(</span>message<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> <span class="token operator">...</span>optionalParams<span class="token operator">:</span> <span class="token builtin">unknown</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span></span>
<span class="line">  <span class="token function">error</span><span class="token punctuation">(</span>message<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> <span class="token operator">...</span>optionalParams<span class="token operator">:</span> <span class="token builtin">unknown</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span></span>
<span class="line">  log<span class="token operator">?</span><span class="token punctuation">(</span>message<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> <span class="token operator">...</span>optionalParams<span class="token operator">:</span> <span class="token builtin">unknown</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span></span>
<span class="line">  trace<span class="token operator">?</span><span class="token punctuation">(</span>message<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> <span class="token operator">...</span>optionalParams<span class="token operator">:</span> <span class="token builtin">unknown</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="default-implementation-consolelogger" tabindex="-1"><a class="header-anchor" href="#default-implementation-consolelogger"><span>Default Implementation: ConsoleLogger</span></a></h4>
<p>The built-in logger is implemented as <code v-pre>ConsoleLogger</code> and is used automatically unless you override it.</p>
<p>Internally, it:</p>
<ul>
<li>Filters messages based on the <code v-pre>stone.logger.level</code> set in the blueprint.</li>
<li>Supports an optional timestamp prefix using <code v-pre>stone.logger.useTimestamp</code>.</li>
<li>Can print colored output when supported via <code v-pre>stone.logger.useColors</code>.</li>
<li>Automatically enables verbose logging when <code v-pre>stone.debug</code> is set to <code v-pre>true</code>.</li>
</ul>
<p>Here’s a typical usage:</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line">Logger<span class="token punctuation">.</span><span class="token function">debug</span><span class="token punctuation">(</span><span class="token string">'This will only be shown if log level is debug or lower'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">Logger<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span><span class="token string">'Something went wrong'</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> context<span class="token operator">:</span> <span class="token string">'ServiceX'</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p>This logger is available immediately after the blueprint is initialized and is accessible from anywhere in your application.</p>
<p>The behavior is context-aware — meaning you don’t need to manually check log levels or environment conditions. Stone.js handles that based on your blueprint settings.</p>
<h3 id="configuring-the-logger" tabindex="-1"><a class="header-anchor" href="#configuring-the-logger"><span>Configuring the Logger</span></a></h3>
<p>Stone.js uses the blueprint as the single source of truth for all logger configuration. You don’t need to hardcode log levels or timestamps — just define your preferences, and the logger will adapt automatically across your entire application.</p>
<h4 id="available-configuration-keys" tabindex="-1"><a class="header-anchor" href="#available-configuration-keys"><span>Available Configuration Keys</span></a></h4>
<p>You can set the following options in your blueprint:</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line">blueprint<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">'stone.logger.level'</span><span class="token punctuation">,</span> <span class="token string">'debug'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>     <span class="token comment">// Minimum log level</span></span>
<span class="line">blueprint<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">'stone.logger.useTimestamp'</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Include timestamps in logs</span></span>
<span class="line">blueprint<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">'stone.logger.useColors'</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// Colored output (when supported)</span></span>
<span class="line">blueprint<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">'stone.debug'</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span>             <span class="token comment">// Force all logs, even in production</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>These options work together to determine whether and how logs are shown. For example:</p>
<ul>
<li>If <code v-pre>stone.logger.level</code> is set to <code v-pre>&quot;warn&quot;</code>, then only <code v-pre>warn()</code> and <code v-pre>error()</code> messages will be printed.</li>
<li>If <code v-pre>stone.debug</code> is set to <code v-pre>true</code>, it overrides the level and prints everything regardless of the level setting.</li>
<li>If <code v-pre>stone.logger.useTimestamp</code> is <code v-pre>true</code>, each message will be prefixed with the current ISO date.</li>
</ul>
<h4 id="supported-log-levels" tabindex="-1"><a class="header-anchor" href="#supported-log-levels"><span>Supported Log Levels</span></a></h4>
<p>Stone.js uses the following enum for log levels:</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">export</span> <span class="token keyword">enum</span> LogLevel <span class="token punctuation">{</span></span>
<span class="line">  <span class="token constant">TRACE</span> <span class="token operator">=</span> <span class="token string">'trace'</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token constant">DEBUG</span> <span class="token operator">=</span> <span class="token string">'debug'</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token constant">INFO</span> <span class="token operator">=</span> <span class="token string">'info'</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token constant">WARN</span> <span class="token operator">=</span> <span class="token string">'warn'</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token constant">ERROR</span> <span class="token operator">=</span> <span class="token string">'error'</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>The default level is <code v-pre>&quot;error&quot;</code> if no level is specified.</p>
<h4 id="example" tabindex="-1"><a class="header-anchor" href="#example"><span>Example</span></a></h4>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> LogLevel <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@stone-js/core'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">blueprint<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">'stone.logger.level'</span><span class="token punctuation">,</span> LogLevel<span class="token punctuation">.</span><span class="token constant">DEBUG</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">blueprint<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">'stone.logger.useTimestamp'</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">blueprint<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">'stone.logger.useColors'</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>This setup ensures that your logs are verbose, readable, and timestamped — ideal for development or debugging sessions.</p>
<h2 id="customizing-the-logger" tabindex="-1"><a class="header-anchor" href="#customizing-the-logger"><span>Customizing the Logger</span></a></h2>
<p>Stone.js is not opinionated about how you log — it simply defines an interface and lets you plug in whatever tool fits your needs. If the built-in <code v-pre>ConsoleLogger</code> doesn’t meet your requirements, you can replace it with your own implementation.</p>
<p>You might want to customize the logger if:</p>
<ul>
<li>You need file-based or remote logging (e.g. writing to disk, HTTP, Elasticsearch).</li>
<li>You use an external logging system like <code v-pre>pino</code>, <code v-pre>winston</code>, or <code v-pre>bunyan</code>.</li>
<li>You want to apply custom formatting, redaction, or metadata.</li>
</ul>
<p>Stone.js allows you to create a logger using either a <strong>class</strong> or a <strong>factory function</strong>, as long as it implements the <code v-pre>ILogger</code> interface.</p>
<h3 id="defining-a-custom-logger" tabindex="-1"><a class="header-anchor" href="#defining-a-custom-logger"><span>Defining a Custom Logger</span></a></h3>
<Tabs id="205" :data='[{"id":"Class-based"},{"id":"Factory-based"}]' :active="0" tab-id="class-factory-function">
<template #title0="{ value, isActive }">Class-based</template>
<template #title1="{ value, isActive }">Factory-based</template>
<template #tab0="{ value, isActive }">
<h4 id="class-based-logger" tabindex="-1"><a class="header-anchor" href="#class-based-logger"><span>Class-based Logger</span></a></h4>
<p>This approach gives you full control and access to the blueprint.</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ILogger <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@stone-js/core'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">MyCustomLogger</span> <span class="token keyword">implements</span> <span class="token class-name">ILogger</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token function">constructor</span><span class="token punctuation">(</span><span class="token keyword">private</span> <span class="token keyword">readonly</span> options<span class="token operator">:</span> <span class="token punctuation">{</span> blueprint <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">info</span><span class="token punctuation">(</span>message<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token operator">:</span> <span class="token builtin">unknown</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// custom info implementation</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">debug</span><span class="token punctuation">(</span>message<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token operator">:</span> <span class="token builtin">unknown</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// custom debug implementation</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">warn</span><span class="token punctuation">(</span>message<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token operator">:</span> <span class="token builtin">unknown</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// custom warn implementation</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">error</span><span class="token punctuation">(</span>message<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token operator">:</span> <span class="token builtin">unknown</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token comment">// custom error implementation</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab1="{ value, isActive }">
<h4 id="factory-based-logger" tabindex="-1"><a class="header-anchor" href="#factory-based-logger"><span>Factory-based Logger</span></a></h4>
<p>This is simpler and works well for wrapping third-party libraries.</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ILogger <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@stone-js/core'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">export</span> <span class="token keyword">const</span> MyCustomLogger <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">{</span> blueprint <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token operator">:</span> ILogger <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token keyword">return</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token function-variable function">info</span><span class="token operator">:</span> <span class="token punctuation">(</span>msg<span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span> <span class="token comment">/* custom info logic */</span> <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">debug</span><span class="token operator">:</span> <span class="token punctuation">(</span>msg<span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span> <span class="token comment">/* custom debug logic */</span> <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">warn</span><span class="token operator">:</span> <span class="token punctuation">(</span>msg<span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span> <span class="token comment">/* custom warn logic */</span> <span class="token punctuation">}</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">error</span><span class="token operator">:</span> <span class="token punctuation">(</span>msg<span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span> <span class="token comment">/* custom error logic */</span> <span class="token punctuation">}</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
</Tabs>
<p>Both approaches give you access to the blueprint, so you can conditionally enable logs, pull log levels, or respect other system settings.</p>
<h3 id="using-a-custom-logger" tabindex="-1"><a class="header-anchor" href="#using-a-custom-logger"><span>Using a Custom Logger</span></a></h3>
<p>Once your custom logger is defined — either as a class or a factory — you don’t need to change how you use logging in your application.<br>
Everything works the same: you can still access the logger via the global singleton or via dependency injection in lifecycle hooks, services, or middleware.</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> Logger <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@stone-js/core'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">export</span> <span class="token keyword">const</span> <span class="token function-variable function">myHandler</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">  Logger<span class="token punctuation">.</span><span class="token function">info</span><span class="token punctuation">(</span><span class="token string">'Custom logger is now active'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Under the hood, the <code v-pre>Logger</code> singleton will delegate to your custom implementation.<br>
So once registered, all logging across your system will automatically route through your logger.</p>
<p>This makes it easy to swap in advanced loggers like Pino, Winston, or your in-house system without rewriting your application logic.</p>
<h3 id="registering-a-custom-logger" tabindex="-1"><a class="header-anchor" href="#registering-a-custom-logger"><span>Registering a Custom Logger</span></a></h3>
<p>To register your custom logger, use the <code v-pre>defineLogger()</code> utility provided by Stone.js. This function tells the system which logger to use and how to instantiate it.</p>
<p>The <code v-pre>defineLogger</code> signature is:</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token function">defineLogger</span><span class="token punctuation">(</span></span>
<span class="line">  logger<span class="token operator">:</span> <span class="token keyword">new</span> <span class="token punctuation">(</span><span class="token operator">...</span>args<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">=></span> ILogger <span class="token operator">|</span> <span class="token punctuation">(</span>options<span class="token operator">:</span> <span class="token punctuation">{</span> blueprint<span class="token operator">:</span> IBlueprint <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token operator">=></span> ILogger<span class="token punctuation">,</span></span>
<span class="line">  isFactory<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">boolean</span><span class="token punctuation">,</span></span>
<span class="line">  config<span class="token operator">?</span><span class="token operator">:</span> Record<span class="token operator">&lt;</span><span class="token builtin">string</span><span class="token punctuation">,</span> <span class="token builtin">unknown</span><span class="token operator">></span></span>
<span class="line"><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li><code v-pre>logger</code>: your custom logger class or factory function.</li>
<li><code v-pre>isFactory</code>: <code v-pre>true</code> if it’s a factory, <code v-pre>false</code> if it’s a class.</li>
<li><code v-pre>config</code>: optional additional settings that will be injected into the blueprint before instantiating the logger.</li>
</ul>
<Tabs id="268" :data='[{"id":"Class-based"},{"id":"Factory-based"}]' :active="0" tab-id="class-factory-function">
<template #title0="{ value, isActive }">Class-based</template>
<template #title1="{ value, isActive }">Factory-based</template>
<template #tab0="{ value, isActive }">
<h4 id="class-based-example" tabindex="-1"><a class="header-anchor" href="#class-based-example"><span>Class-based example</span></a></h4>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> defineLogger <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@stone-js/core'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> MyCustomLogger <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./my-custom-logger'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">blueprint<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token function">defineLogger</span><span class="token punctuation">(</span>MyCustomLogger<span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="registering-with-custom-config" tabindex="-1"><a class="header-anchor" href="#registering-with-custom-config"><span>Registering with custom config</span></a></h4>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line">blueprint<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token function">defineLogger</span><span class="token punctuation">(</span>MyCustomLogger<span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">,</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token string-property property">'stone.logger.level'</span><span class="token operator">:</span> <span class="token string">'debug'</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token string-property property">'stone.logger.useTimestamp'</span><span class="token operator">:</span> <span class="token boolean">true</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab1="{ value, isActive }">
<h4 id="factory-based-example" tabindex="-1"><a class="header-anchor" href="#factory-based-example"><span>Factory-based example</span></a></h4>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> defineLogger <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@stone-js/core'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> MyCustomLogger <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./my-custom-logger'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">blueprint<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token function">defineLogger</span><span class="token punctuation">(</span>MyCustomLogger<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="registering-with-custom-config-1" tabindex="-1"><a class="header-anchor" href="#registering-with-custom-config-1"><span>Registering with custom config</span></a></h4>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line">blueprint<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token function">defineLogger</span><span class="token punctuation">(</span>MyCustomLogger<span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token string-property property">'stone.logger.level'</span><span class="token operator">:</span> <span class="token string">'debug'</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token string-property property">'stone.logger.useTimestamp'</span><span class="token operator">:</span> <span class="token boolean">true</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
</Tabs>
<p>This allows you to register your custom logger and inject any required configuration upfront — no extra boilerplate, just pure context-driven setup.</p>
<h2 id="example-using-pino-with-stone-js" tabindex="-1"><a class="header-anchor" href="#example-using-pino-with-stone-js"><span>Example: Using Pino with Stone.js</span></a></h2>
<p><a href="https://getpino.io/#/" target="_blank" rel="noopener noreferrer">Pino</a> is a high-performance JSON logger, ideal for structured logging in production environments.</p>
<h3 id="installation" tabindex="-1"><a class="header-anchor" href="#installation"><span>Installation</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre v-pre><code><span class="line"><span class="token function">npm</span> <span class="token function">install</span> pino</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="factory-based-implementation" tabindex="-1"><a class="header-anchor" href="#factory-based-implementation"><span>Factory-Based Implementation</span></a></h3>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token comment">// my-pino-logger.ts</span></span>
<span class="line"><span class="token keyword">import</span> pino <span class="token keyword">from</span> <span class="token string">'pino'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ILogger <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@stone-js/core'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">export</span> <span class="token keyword">const</span> MyPinoLogger <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">{</span> blueprint <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token operator">:</span> ILogger <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token keyword">const</span> level <span class="token operator">=</span> blueprint<span class="token punctuation">.</span><span class="token generic-function"><span class="token function">get</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token builtin">string</span><span class="token operator">></span></span></span><span class="token punctuation">(</span><span class="token string">'stone.logger.level'</span><span class="token punctuation">,</span> <span class="token string">'info'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token keyword">const</span> useTimestamp <span class="token operator">=</span> blueprint<span class="token punctuation">.</span><span class="token generic-function"><span class="token function">get</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token builtin">boolean</span><span class="token operator">></span></span></span><span class="token punctuation">(</span><span class="token string">'stone.logger.useTimestamp'</span><span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">  <span class="token keyword">const</span> logger <span class="token operator">=</span> <span class="token function">pino</span><span class="token punctuation">(</span><span class="token punctuation">{</span></span>
<span class="line">    level<span class="token punctuation">,</span></span>
<span class="line">    timestamp<span class="token operator">:</span> useTimestamp <span class="token operator">?</span> pino<span class="token punctuation">.</span>stdTimeFunctions<span class="token punctuation">.</span>isoTime <span class="token operator">:</span> <span class="token boolean">false</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">  <span class="token keyword">return</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token function-variable function">info</span><span class="token operator">:</span> <span class="token punctuation">(</span>msg<span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token punctuation">)</span> <span class="token operator">=></span> logger<span class="token punctuation">.</span><span class="token function">info</span><span class="token punctuation">(</span><span class="token punctuation">{</span> extra<span class="token operator">:</span> params <span class="token punctuation">}</span><span class="token punctuation">,</span> msg<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">debug</span><span class="token operator">:</span> <span class="token punctuation">(</span>msg<span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token punctuation">)</span> <span class="token operator">=></span> logger<span class="token punctuation">.</span><span class="token function">debug</span><span class="token punctuation">(</span><span class="token punctuation">{</span> extra<span class="token operator">:</span> params <span class="token punctuation">}</span><span class="token punctuation">,</span> msg<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">warn</span><span class="token operator">:</span> <span class="token punctuation">(</span>msg<span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token punctuation">)</span> <span class="token operator">=></span> logger<span class="token punctuation">.</span><span class="token function">warn</span><span class="token punctuation">(</span><span class="token punctuation">{</span> extra<span class="token operator">:</span> params <span class="token punctuation">}</span><span class="token punctuation">,</span> msg<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">error</span><span class="token operator">:</span> <span class="token punctuation">(</span>msg<span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token punctuation">)</span> <span class="token operator">=></span> logger<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span><span class="token punctuation">{</span> extra<span class="token operator">:</span> params <span class="token punctuation">}</span><span class="token punctuation">,</span> msg<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">trace</span><span class="token operator">:</span> <span class="token punctuation">(</span>msg<span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token punctuation">)</span> <span class="token operator">=></span> logger<span class="token punctuation">.</span>trace<span class="token operator">?.</span><span class="token punctuation">(</span><span class="token punctuation">{</span> extra<span class="token operator">:</span> params <span class="token punctuation">}</span><span class="token punctuation">,</span> msg<span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">    <span class="token function-variable function">log</span><span class="token operator">:</span> <span class="token punctuation">(</span>msg<span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token punctuation">)</span> <span class="token operator">=></span> logger<span class="token punctuation">.</span><span class="token function">info</span><span class="token punctuation">(</span><span class="token punctuation">{</span> extra<span class="token operator">:</span> params <span class="token punctuation">}</span><span class="token punctuation">,</span> msg<span class="token punctuation">)</span></span>
<span class="line">  <span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="registering-the-factory-based-logger" tabindex="-1"><a class="header-anchor" href="#registering-the-factory-based-logger"><span>Registering the Factory-based Logger</span></a></h3>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> defineLogger <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@stone-js/core'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> MyPinoLogger <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./my-pino-logger'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">blueprint<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token function">defineLogger</span><span class="token punctuation">(</span>MyPinoLogger<span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token string-property property">'stone.logger.level'</span><span class="token operator">:</span> <span class="token string">'debug'</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token string-property property">'stone.logger.useTimestamp'</span><span class="token operator">:</span> <span class="token boolean">true</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="example-using-winston-with-stone-js" tabindex="-1"><a class="header-anchor" href="#example-using-winston-with-stone-js"><span>Example: Using Winston with Stone.js</span></a></h2>
<p><a href="https://github.com/winstonjs/winston" target="_blank" rel="noopener noreferrer">Winston</a> is a flexible logger with support for multiple transports (console, file, HTTP, etc).</p>
<h3 id="installation-1" tabindex="-1"><a class="header-anchor" href="#installation-1"><span>Installation</span></a></h3>
<div class="language-bash line-numbers-mode" data-highlighter="prismjs" data-ext="sh"><pre v-pre><code><span class="line"><span class="token function">npm</span> <span class="token function">install</span> winston</span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h3 id="class-based-implementation" tabindex="-1"><a class="header-anchor" href="#class-based-implementation"><span>Class-Based Implementation</span></a></h3>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token comment">// my-winston-logger.ts</span></span>
<span class="line"><span class="token keyword">import</span> winston <span class="token keyword">from</span> <span class="token string">'winston'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> ILogger<span class="token punctuation">,</span> IBlueprint <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@stone-js/core'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">MyWinstonLogger</span> <span class="token keyword">implements</span> <span class="token class-name">ILogger</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token keyword">private</span> <span class="token keyword">readonly</span> logger<span class="token operator">:</span> winston<span class="token punctuation">.</span>Logger<span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">constructor</span><span class="token punctuation">(</span><span class="token punctuation">{</span> blueprint <span class="token punctuation">}</span><span class="token operator">:</span> <span class="token punctuation">{</span> blueprint<span class="token operator">:</span> IBlueprint <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">const</span> level <span class="token operator">=</span> blueprint<span class="token punctuation">.</span><span class="token generic-function"><span class="token function">get</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token builtin">string</span><span class="token operator">></span></span></span><span class="token punctuation">(</span><span class="token string">'stone.logger.level'</span><span class="token punctuation">,</span> <span class="token string">'info'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">    <span class="token keyword">const</span> useTimestamp <span class="token operator">=</span> blueprint<span class="token punctuation">.</span><span class="token generic-function"><span class="token function">get</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token builtin">boolean</span><span class="token operator">></span></span></span><span class="token punctuation">(</span><span class="token string">'stone.logger.useTimestamp'</span><span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">    <span class="token keyword">this</span><span class="token punctuation">.</span>logger <span class="token operator">=</span> winston<span class="token punctuation">.</span><span class="token function">createLogger</span><span class="token punctuation">(</span><span class="token punctuation">{</span></span>
<span class="line">      level<span class="token punctuation">,</span></span>
<span class="line">      format<span class="token operator">:</span> winston<span class="token punctuation">.</span>format<span class="token punctuation">.</span><span class="token function">combine</span><span class="token punctuation">(</span></span>
<span class="line">        <span class="token operator">...</span><span class="token punctuation">(</span>useTimestamp</span>
<span class="line">          <span class="token operator">?</span> <span class="token punctuation">[</span>winston<span class="token punctuation">.</span>format<span class="token punctuation">.</span><span class="token function">timestamp</span><span class="token punctuation">(</span><span class="token punctuation">{</span> format<span class="token operator">:</span> <span class="token string">'YYYY-MM-DD HH:mm:ss'</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">]</span></span>
<span class="line">          <span class="token operator">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">        winston<span class="token punctuation">.</span>format<span class="token punctuation">.</span><span class="token function">printf</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">{</span> timestamp<span class="token punctuation">,</span> level<span class="token punctuation">,</span> message<span class="token punctuation">,</span> <span class="token operator">...</span>meta <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span></span>
<span class="line">          <span class="token keyword">const</span> base <span class="token operator">=</span> useTimestamp <span class="token operator">?</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">[</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>timestamp<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">]</span><span class="token template-punctuation string">`</span></span> <span class="token operator">:</span> <span class="token string">''</span><span class="token punctuation">;</span></span>
<span class="line">          <span class="token keyword">const</span> extras <span class="token operator">=</span> Object<span class="token punctuation">.</span><span class="token function">keys</span><span class="token punctuation">(</span>meta<span class="token punctuation">)</span><span class="token punctuation">.</span>length <span class="token operator">?</span> <span class="token constant">JSON</span><span class="token punctuation">.</span><span class="token function">stringify</span><span class="token punctuation">(</span>meta<span class="token punctuation">)</span> <span class="token operator">:</span> <span class="token string">''</span><span class="token punctuation">;</span></span>
<span class="line">          <span class="token keyword">return</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>base<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>level<span class="token punctuation">.</span><span class="token function">toUpperCase</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>message<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>extras<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">;</span></span>
<span class="line">        <span class="token punctuation">}</span><span class="token punctuation">)</span></span>
<span class="line">      <span class="token punctuation">)</span><span class="token punctuation">,</span></span>
<span class="line">      transports<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token keyword">new</span> <span class="token class-name">winston</span><span class="token punctuation">.</span>transports<span class="token punctuation">.</span><span class="token function">Console</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">]</span></span>
<span class="line">    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">info</span><span class="token punctuation">(</span>message<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token operator">:</span> <span class="token builtin">unknown</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">this</span><span class="token punctuation">.</span>logger<span class="token punctuation">.</span><span class="token function">info</span><span class="token punctuation">(</span>message<span class="token punctuation">,</span> <span class="token punctuation">{</span> extra<span class="token operator">:</span> params <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">debug</span><span class="token punctuation">(</span>message<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token operator">:</span> <span class="token builtin">unknown</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">this</span><span class="token punctuation">.</span>logger<span class="token punctuation">.</span><span class="token function">debug</span><span class="token punctuation">(</span>message<span class="token punctuation">,</span> <span class="token punctuation">{</span> extra<span class="token operator">:</span> params <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">warn</span><span class="token punctuation">(</span>message<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token operator">:</span> <span class="token builtin">unknown</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">this</span><span class="token punctuation">.</span>logger<span class="token punctuation">.</span><span class="token function">warn</span><span class="token punctuation">(</span>message<span class="token punctuation">,</span> <span class="token punctuation">{</span> extra<span class="token operator">:</span> params <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">error</span><span class="token punctuation">(</span>message<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token operator">:</span> <span class="token builtin">unknown</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">this</span><span class="token punctuation">.</span>logger<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span>message<span class="token punctuation">,</span> <span class="token punctuation">{</span> extra<span class="token operator">:</span> params <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  trace<span class="token operator">?</span><span class="token punctuation">(</span>message<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token operator">:</span> <span class="token builtin">unknown</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">this</span><span class="token punctuation">.</span>logger<span class="token punctuation">.</span>verbose<span class="token operator">?.</span><span class="token punctuation">(</span>message<span class="token punctuation">,</span> <span class="token punctuation">{</span> extra<span class="token operator">:</span> params <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  log<span class="token operator">?</span><span class="token punctuation">(</span>message<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> <span class="token operator">...</span>params<span class="token operator">:</span> <span class="token builtin">unknown</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">this</span><span class="token punctuation">.</span>logger<span class="token punctuation">.</span><span class="token function">info</span><span class="token punctuation">(</span>message<span class="token punctuation">,</span> <span class="token punctuation">{</span> extra<span class="token operator">:</span> params <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="registering-the-class-based-logger" tabindex="-1"><a class="header-anchor" href="#registering-the-class-based-logger"><span>Registering the Class-Based Logger</span></a></h3>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> defineLogger <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@stone-js/core'</span><span class="token punctuation">;</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> MyWinstonLogger <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./my-winston-logger'</span><span class="token punctuation">;</span></span>
<span class="line"></span>
<span class="line">blueprint<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token function">defineLogger</span><span class="token punctuation">(</span>MyWinstonLogger<span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">,</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token string-property property">'stone.logger.level'</span><span class="token operator">:</span> <span class="token string">'debug'</span><span class="token punctuation">,</span></span>
<span class="line">  <span class="token string-property property">'stone.logger.useTimestamp'</span><span class="token operator">:</span> <span class="token boolean">true</span></span>
<span class="line"><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>These examples give you real-world logging power while staying fully compatible with Stone.js.</p>
<h2 id="best-practices" tabindex="-1"><a class="header-anchor" href="#best-practices"><span>Best Practices</span></a></h2>
<p>Use these guidelines to ensure that logging in your Stone.js application remains clean, efficient, and maintainable:</p>
<h4 id="prefer-dependency-injection-over-global-access" tabindex="-1"><a class="header-anchor" href="#prefer-dependency-injection-over-global-access"><span>Prefer dependency injection over global access</span></a></h4>
<p>Always use the injected <code v-pre>logger</code> when you're inside:</p>
<ul>
<li>a lifecycle hook</li>
<li>a blueprint middleware</li>
<li>a service constructor</li>
</ul>
<p>Avoid importing and using the <code v-pre>Logger</code> singleton in places where dependency injection is possible. This keeps your code decoupled and testable.</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line"><span class="token comment">// ✅ Preferred</span></span>
<span class="line"><span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">MyService</span> <span class="token punctuation">{</span></span>
<span class="line">  <span class="token keyword">private</span> <span class="token keyword">readonly</span> logger<span class="token operator">:</span> ILogger<span class="token punctuation">;</span></span>
<span class="line">  <span class="token function">constructor</span><span class="token punctuation">(</span><span class="token punctuation">{</span> logger <span class="token punctuation">}</span><span class="token operator">:</span> <span class="token punctuation">{</span> logger<span class="token operator">:</span> ILogger <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">this</span><span class="token punctuation">.</span>logger <span class="token operator">=</span> logger<span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line">  <span class="token function">doSomething</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span>
<span class="line">    <span class="token keyword">this</span><span class="token punctuation">.</span>logger<span class="token punctuation">.</span><span class="token function">debug</span><span class="token punctuation">(</span><span class="token string">'Doing something'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">  <span class="token punctuation">}</span></span>
<span class="line"><span class="token punctuation">}</span></span>
<span class="line"></span>
<span class="line"><span class="token comment">// 🚫 Avoid (hard to test and mock)</span></span>
<span class="line"><span class="token keyword">import</span> <span class="token punctuation">{</span> Logger <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@stone-js/core'</span><span class="token punctuation">;</span></span>
<span class="line">Logger<span class="token punctuation">.</span><span class="token function">info</span><span class="token punctuation">(</span><span class="token string">'Direct usage'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="centralize-logging-configuration" tabindex="-1"><a class="header-anchor" href="#centralize-logging-configuration"><span>Centralize logging configuration</span></a></h4>
<p>Use the blueprint to set all logger-related options. Avoid hardcoding log levels or formatting rules inside your code.</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line">blueprint<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">'stone.logger.level'</span><span class="token punctuation">,</span> <span class="token string">'info'</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line">blueprint<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">'stone.logger.useTimestamp'</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">;</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><p>This ensures consistency across environments and makes it easier to switch logging strategies later.</p>
<h4 id="be-selective-with-verbosity" tabindex="-1"><a class="header-anchor" href="#be-selective-with-verbosity"><span>Be selective with verbosity</span></a></h4>
<ul>
<li>Use <code v-pre>debug()</code> for developer-only insights.</li>
<li>Use <code v-pre>info()</code> for general application state.</li>
<li>Use <code v-pre>warn()</code> for unexpected but non-fatal conditions.</li>
<li>Use <code v-pre>error()</code> only when something truly failed and should be investigated.</li>
<li>Use <code v-pre>trace()</code> sparingly — it's meant for very fine-grained diagnostics.</li>
</ul>
<p>Don’t log everything all the time — too much logging can hide real problems in a sea of noise.</p>
<h4 id="avoid-logging-sensitive-data" tabindex="-1"><a class="header-anchor" href="#avoid-logging-sensitive-data"><span>Avoid logging sensitive data</span></a></h4>
<p>Even though logs are meant for diagnostics, never log passwords, tokens, personal identifiers, or any confidential business logic. If needed, use redaction libraries or manual masking.</p>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line">logger<span class="token punctuation">.</span><span class="token function">info</span><span class="token punctuation">(</span><span class="token string">'User login'</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> username <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// ✅ okay</span></span>
<span class="line">logger<span class="token punctuation">.</span><span class="token function">info</span><span class="token punctuation">(</span><span class="token string">'Token:'</span><span class="token punctuation">,</span> token<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 🚫 avoid this</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="customize-your-logger-when-needed" tabindex="-1"><a class="header-anchor" href="#customize-your-logger-when-needed"><span>Customize your logger when needed</span></a></h4>
<p>When you're ready to move beyond the console:</p>
<ul>
<li>Choose <code v-pre>pino</code> for speed and structured logs.</li>
<li>Choose <code v-pre>winston</code> for flexibility and multiple output targets.</li>
<li>Choose your own tool if it fits your ecosystem.</li>
</ul>
<p>Stone.js makes swapping the logger easy — just implement the <code v-pre>ILogger</code> interface and register it via <code v-pre>defineLogger()</code>.</p>
<h4 id="keep-log-messages-meaningful" tabindex="-1"><a class="header-anchor" href="#keep-log-messages-meaningful"><span>Keep log messages meaningful</span></a></h4>
<p>Treat log messages like code comments. They should:</p>
<ul>
<li>Describe what happened</li>
<li>Be human-readable</li>
<li>Help future-you debug an issue</li>
</ul>
<div class="language-typescript line-numbers-mode" data-highlighter="prismjs" data-ext="ts"><pre v-pre><code><span class="line">logger<span class="token punctuation">.</span><span class="token function">info</span><span class="token punctuation">(</span><span class="token string">'User created'</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> userId <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// ✅</span></span>
<span class="line">logger<span class="token punctuation">.</span><span class="token function">debug</span><span class="token punctuation">(</span><span class="token string">'Something happened'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 🚫 too vague</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="summary" tabindex="-1"><a class="header-anchor" href="#summary"><span>Summary</span></a></h2>
<p>Logging in Stone.js is simple, flexible, and built to scale with your application.</p>
<p>Out of the box, you get a lightweight, console-based logger that’s fully integrated into the framework. It’s available globally via a singleton and is automatically injected into your context where appropriate — services, middleware, lifecycle hooks, and more.</p>
<p>You can configure its behavior through the blueprint, adjusting verbosity, timestamp formatting, and debug mode. When you're ready to move beyond the basics, you can easily replace the logger with your own class or factory — whether that’s wrapping a library like Pino or Winston, or building a completely custom solution.</p>
<p>Stone.js doesn’t lock you into one way of doing things — it gives you a common interface, a clean contract, and the freedom to extend logging in a way that fits your needs.</p>
<p><strong>Quick recap:</strong></p>
<ul>
<li>Use the logger via <code v-pre>Logger</code> or inject it where available.</li>
<li>Configure it with <code v-pre>stone.logger.level</code>, <code v-pre>useTimestamp</code>, and <code v-pre>stone.debug</code>.</li>
<li>Implement <code v-pre>ILogger</code> if you want to customize.</li>
<li>Register your logger using <code v-pre>defineLogger()</code> — class or factory, your choice.</li>
<li>Log intentionally. Debug confidently. Deploy with traceability.</li>
</ul>
<p>That's it — you're now fully equipped to tame your logs in the Continuum.</p>
</div></template>


